#!/usr/bin/env bash

#
basedir=/Users/book/KOALA/PhenomXCP/issues

# Collection of NR data
# --
# # $basedir/1_collect_nr_data_version2.py

# Optional diagnostic potting
# --
# $basedir/2a_plot_amp_fitting_region_diagnostic.py
# $basedir/2b_plot_dphi_fitting_region_diagnostic.py

# Collect metadata for parameter space fits
# --
# $basedir/3a_collect_metadata.py

# Fit waveforms and organize metadata
# --
# $basedir/3b_plot_prefit_diagnostic.py
$basedir/3c_fit_waveforms.py

# Fit model parameters across physical parameter space and then document
# --
$basedir/4a_fit_hyper_parameters.py
$basedir/4b_document_fits.py

# # Generate late stage diagnostic plots
# # --
# $basedir/5a_plot_comparisons.py
# $basedir/5b_phase_function_diagnostic.py